#!/bin/bash

: 'CODE_INTERVIEW
  - Some classic coding interview style problems
    solved in Bash
CODE_INTERVIEW'

fibonacci(){
  #displays the first ten elements in the Fibonacci Series

  first_num=0
  sec_num=1
  thir_num=0
  fibo_ser[0]="$first_num"
  fibo_ser[1]="$sec_num"

  while [[ ${#fibo_ser[@]} -lt 10 ]] ; do
      thir_num=$((first_num+sec_num)) 
      first_num=$sec_num
      sec_num=$thir_num
      fibo_ser+=("$thir_num")
      continue
  done
  echo "${fibo_ser[@]}"
}
fibonacci
