#!/bin/bash
#Gross margin program for input component prices
#program must run on MAC / BSD systems


#create arrays for variable storage
item_name=()
item_price=()


function uppercase() {
    #translate a string into all uppercase letters (to minimize user input error)
    #BSD does not support parameter substitution
    word=$(echo $1 | sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/')
    echo $word
}

function runloops() {
    #function will prompt user for individual fixture names
    #function will aggregate costs for fixture subcomponents
    #function will append to an array of fixture names (item_name)
    #function will append costs to an array of aggragated costs (item_price)
    #arrays will map to each other (${item_name[0]}:${item_price[0]})
	while : ;do
	    item=1
	    prodprice=0
	    read -p "Please enter the name of the item: " fixture
	    item_name+=("$fixture")
		while : ;do
		    #acquire cost of first component
		    read -p "Please enter cost of component $item: " cost
		    [[ ! $cost =~ ^[0-9]*\.?[0-9]*$ ]] && echo "Cost must be a in integer format
		Please try again" && continue
		    #acquire quantity of specified component 
		    read -p "Please enter quantity of component $item: " quant
		    while [[ ! $quant =~ ^[0-9]*\.?[0-9]*$ ]];do
			echo "Quantity must be in integer format 
		Please try again"   
			read -p "Please enter quantity of item $item: " quant
		    done
		    
		    #calculate the total cost of the component
		    totprice=$(( cost * quant ))
		    echo "Price of component ${item} is \$$totprice"
		    
		    #since a fixture could have multiple components: 
		    #add the component price, to the master total price (prodprice) initialized outside of the loop
		    prodprice=$((totprice + prodprice))
		    ((++item))
		    
		    read -p "Are there more components associated with the fixture? {yes | no}: " comprompt
		    uppercase $comprompt
		    while [[ $word != "YES" && $word != "NO" ]];do
			read -p "Please input either 'yes' or 'no': " comprompt
			uppercase $comprompt
		    done
		    comprompt=$word
		    [[ $comprompt =~ "NO" ]] && break || continue
		done 
            item_price+=("\$$prodprice")
	    read -p "Would you like to input costs for more fixtures? {yes | no}: " fixprompt
	    uppercase $fixprompt
	    while [[ $word != "YES" && $word != "NO" ]];do
		 read -p "Please input either 'yes' or 'no': " fixprompt
		 uppercase $fixprompt
	    done
	    fixprompt=$word
	    [[ $fixprompt =~ "NO" ]] && break || continue
	done
}

runloops

item_counter=-1
for i in ${item_name[*]}; do
    ((item_counter++))
    echo "${item_name[$item_counter]}=${item_price[$item_counter]}"
done

#commit_test
