#!/bin/bash
#If run with the initial argument 'test', will take in the provided array values

PATH=${PATH}:$(pwd)
mistake=false

if [[ $# != 0 ]];then
    if [[ $1 =~ "test" ]];then
        item_name=("test fixture 1" "test fixture 2")    
        item_price=(\$490 \$560)
    elif [[ $1 != "test" ]];then
        input=$1
        input=${input^^}
        while [[ $input != "TEST" ]];do
            read -p "Please enter 'test' if you would like to use preset array values,
or leave blank to run the prompt script: " input
            [[ $input =~ "" ]] && mistake=true && break
            continue
        done
   fi
else
    source cost   
fi

[[ $mistake = true ]] && source cost

############################################################################################
#section below is mainly for testing, assurance that array values were sourced properly
echo "Array values in the current shell:"
echo ${item_name[@]}
echo ${item_price[@]}

############################################################################################
#Next section will allow the user to select the specific array entry to determine margin of
